const express = require('express')
const cors = require('cors')

const root = require('../routes/root/root')
// Import authentication routes
const user = require('../routes/auth/local')
const google = require('../routes/auth/google')
const facebook = require('../routes/auth/facebook')
// Import api routes
const startUp = require('../routes/api/cvBits/startUp')
const personalInfo = require('../routes/api/cvBits/personalInfo')
const contactInfo = require('../routes/api/cvBits/contactInfo')
const personalSummary = require('../routes/api/cvBits/personalSummary')
const employHistory = require('../routes/api/cvBits/employHistory')
const experience = require('../routes/api/cvBits/experience')
const firstImpression = require('../routes/api/cvBits/firstImpression')
const secondEdu = require('../routes/api/cvBits/secondEdu')
const tertEdu = require('../routes/api/cvBits/tertEdu')
const language = require('../routes/api/cvBits/language')
const skill = require('../routes/api/cvBits/skill')
const attribute = require('../routes/api/cvBits/attribute')
const interest = require('../routes/api/cvBits/interest')
const reference = require('../routes/api/cvBits/reference')
const photo = require('../routes/api/cvBits/photo')
const certificate = require('../routes/api/cvBits/certificate')
const curriculumVitae = require('../routes/api/curriculumVitae/curriculumVitae')
const device = require('../routes/api/devices/device')
const affiliate = require('../routes/staff/affiliate')
const config = require('../routes/api/config/config')
const error = require('../routes/error/error')
// Import service routes
// const photoService = require('../routes/api/services/awsS3Photo')
const shareCV = require('../routes/api/shareCV/shareCV')
const cloudinary = require('../routes/api/services/cloudinary')

module.exports = (app) => {
  // Express middleware
  app.use(express.urlencoded({ extended: true }))
  app.use(express.json())
  app.use(cors())

  app.use('/', root)
  // Use authentication routes
  app.use('/auth/user', user)
  app.use('/auth/google', google)
  app.use('/auth/facebook', facebook)
  app.use('/auth/device', device)
  // Use api routes
  app.use('/api/start-up', startUp)
  app.use('/api/personal-info', personalInfo)
  app.use('/api/contact-info', contactInfo)
  app.use('/api/personal-summary', personalSummary)
  app.use('/api/employment-history', employHistory)
  app.use('/api/experience', experience)
  app.use('/api/first-impression', firstImpression)
  app.use('/api/secondary-education', secondEdu)
  app.use('/api/tertiary-education', tertEdu)
  app.use('/api/language', language)
  app.use('/api/skill', skill)
  app.use('/api/attribute', attribute)
  app.use('/api/interest', interest)
  app.use('/api/reference', reference)
  app.use('/api/photo', photo)
  app.use('/api/certificate', certificate)
  // Use service routes
  // app.use('/api/photo-service', photoService)
  app.use('/api/cloudinary', cloudinary)
  app.use('/api/share-cv', shareCV)
  app.use('/api/curriculum-vitae', curriculumVitae)
  app.use('/api/config', config)
  app.use('/error', error)
  // Use staff routes
  app.use('/api/affiliate', affiliate)
}
